### ISSUE TITLE
json key letter case 

### ISSUE THREAD

**Issue by tangyumeng** [lonnng/yue#1]
curl -XPOST -d '{"title":"title", "desc":"desc","count":3,"number":"1222","attachment":["tag1","tag2","tag3"]}' http://localhost:8080/clues

post 数据后，

curl http://localhost:8080/clues  获取列表，Data 部分怎样设置才能返回 key 为"data",而不是 "Data".

protocol.go 里面 已经是  
Data string `json:"data"`。
没起作用，不太明白。

**Comment by tangyumeng** [comment]
找到问题了，忽略。

**Comment by tangyumeng** [comment]
``` golang
type ClueListResponse struct {
    Code int        `json:"code"`
    Data []ClueInfo `json:"data"`
}  
```

ClueListResponse 结构体改成这样就可以了

**Comment by lonng** [comment]
哦，之前忘记加了

**Comment by lonng** [comment]
ok了
