### ISSUE TITLE
postman载入文件时错误

### ISSUE THREAD

**Issue by painkiller0513** [lonnng/yue#2]

**Comment by painkiller0513** [comment]
项目中的.json文件，载入到postman中解析错误。POSTMAN版本4.2.0

**Comment by painkiller0513** [comment]
下载了最新版本的POSTMAN已经可以了。

**Comment by lonng** [comment]
恩，后面我补充一个直接用curl版本的上去。

武羡峰 <notifications@github.com>于2017年1月26日星期四 20:27写道：
